version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "ci(deps)"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"
    rebase-strategy: auto
    versioning-strategy: increase
    cooldown:
      default-days: 3
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps)"
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
